# ptrs
cc_library(
    name = "ptrs_unique_ptr_util",
    srcs = ["ptrs/unique_ptr_util.cc"],
    hdrs = ["ptrs/unique_ptr_util.h"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "ptrs_shared_ptr_util",
    srcs = ["ptrs/shared_ptr_util.cc"],
    hdrs = ["ptrs/shared_ptr_util.h"],
    visibility = ["//main:__pkg__"],
)

# time
cc_library(
    name = "time_time",
    srcs = ["time/time.cc"],
    hdrs = ["time/time.h"],
    visibility = ["//main:__pkg__"],
)

# exceptions
cc_library(
    name = "exceptions_exceptions",
    srcs = ["exceptions/exceptions.cc"],
    hdrs = ["exceptions/exceptions.h"],
    visibility = ["//main:__pkg__"],
)

# threads
cc_library(
    name = "threads_thread_util",
    srcs = ["threads/thread_util.cc"],
    hdrs = ["threads/thread_util.h"],
    visibility = ["//main:__pkg__"],
)

# containers
cc_library(
    name = "containers_heap_demo",
    srcs = [],
    hdrs = ["containers/heap_demo.h"],
    visibility = ["//main:__pkg__"],
)
