

# main_ptrs
cc_binary(
    name = "main_ptrs",
    srcs = ["main_ptrs.cc"],
    deps = [
        "//lib:ptrs_unique_ptr_util",
        "//lib:ptrs_shared_ptr_util",
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_exceptions
cc_binary(
    name = "main_exceptions",
    srcs = ["main_exceptions.cc"],
    deps = [
#        ":hello-greet",
        "//lib:exceptions_exceptions",
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_threads
cc_binary(
    name = "main_threads",
    srcs = ["main_threads.cc"],
    deps = [
        "//lib:threads_thread_util",
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_time
cc_binary(
    name = "main_time",
    srcs = ["main_time.cc"],
    deps = [
        "//lib:time_time",
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_enable_if
cc_binary(
    name = "main_enable_if",
    srcs = ["main_enable_if.cc"],
    deps = [
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_others
cc_binary(
    name = "main_others",
    srcs = ["main_others.cc"],
    deps = [
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

# main_containers
cc_binary(
    name = "main_containers",
    srcs = ["main_containers.cc"],
    deps = [
        "//lib:containers_heap_demo",
    ],
    linkopts = [
        "-std=c++11",
    ], 
)

